"""initial schema

Revision ID: f901f3dace41
Revises: 
Create Date: 2026-05-21 16:00:41.898166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f901f3dace41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('stored_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('files_uploaded', sa.Integer(), nullable=False),
    sa.Column('files_downloaded', sa.Integer(), nullable=False),
    sa.Column('had_conflicts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_file_path'), 'versions', ['file_path'], unique=False)
    op.create_table('manifest_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sync_event_id'], ['sync_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_event_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_event_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sync_event_id'], ['sync_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_event_files')
    op.drop_table('manifest_snapshots')
    op.drop_index(op.f('ix_versions_file_path'), table_name='versions')
    op.drop_table('versions')
    op.drop_table('sync_events')
    op.drop_table('files')
    op.drop_table('devices')
    # ### end Alembic commands ###
